### ISSUE TITLE
Missing IHttpClientFactory variable from constructor in your sample code

### ISSUE THREAD

**Issue by mogstuff** [XeroAPI/Xero-NetStandard#107]
If I try to run the sample code provided, there is a compilation error for this line:

var client = new XeroClient(xeroConfig);

There is no argument given that responds to the formal parameter IHttpClientFactory of XeroClient.XeroClient(XeroConfiguration, IHttpClientFactory)

Is the README out of date or am I missing something?

**Comment by mogstuff** [comment]
I can see you have updated the README 

//In the example app, I've used the config via appsettings so it becomes:
var client = new Xero.NetStandard.OAuth2.Client.XeroClient(config.Value, httpClientFactory);

Where is httpClientFactory defined at please? how is this implemented?

**Comment by shereenfathima** [comment]
@mogstuff Did you find a solution for httpClientFactory? How can I initiate the variable to use in the MVC app

**Comment by jenksguo** [comment]
Documentation updated to include an MVC example. Please read README.md again. :-)

**Comment by KenYarborough** [comment]
Note that the name of this project is "Xero-NetStandard"

Multiple programmers have mentioned IHttpClientFactory breaks the code.

The reason is simple: IHttpClientFactory is a DotNet core feature (added in DotNet Core 2.1)

The HttpClientFactory is fantastic if you're the 5% using DotNet Core, and the library was called "Xero-NetCore"

Not useful in a library called "Xero-NetStandard"

I'm not the first programmer to report this problem.

I'm really irritated that the only documentation is in the "MD" file, which @jenksguo updated, without obviously testing, and then immediately closed.

He just passed the buck. In the code example buried in the MD file:

by making a class with "using Microsoft.AspNetCore.Mvc;"

with the note "a .NET Core Mvc example:"

meaning you have to call the class from DotNet core class to make work.

Sort of defeats the purpose of a library called "Xero-NetStandard"

So to repeat myself: if a library is called "Xero-NetStandard", no one is interested in a "a .NET Core Mvc example:"

Please fix. Some of us are actually trying to use a Xero.
