### ISSUE TITLE
SummarizeErrors

### ISSUE THREAD

**Issue by afscfl** [XeroAPI/Xero-NetStandard#108]
Xero.NetStandard.OAuth2 - version 0.1.0
Xero.NetStandard.OAuth2Client - version 0.0.2

I am trying to create multiple invoices with the method CreateInvoicesAsync and setting summarizeErrors = false. 
If an issue happens like, contact not found or any other validation error for one of the invoices, I am getting a 400 validation exception and not 200 Ok with a list of invoices with their status.

Any ideas

Regards,
Afsal

**Comment by SidneyAllen** [comment]
@afscfl - thanks for the feedback.

Our new OAuth 2 SDKs are all being generated from our OpenAPI specs.  We've seen this issue in other language SDKs and will work to address it for .NET as well.

**Comment by MrSHovel** [comment]
I'm in the process of converting our old original API code to the new OAuth code have have struck this issue. In the old code I called **UpdateOrCreate<Contact>(ContactCollection)** and this would "Update" OR "Create" the passed in Contacts.
I though using the new method **CreateContactsAsync** with my ContactCollection and passing in _false_ for the summarizeErrors parameter would give me the same functionality, but it just throws an exception and doesn't return the ContactCollection with separate validation data. 

Is this the same bug and does this mean all updates using collections (batching) will suffer problem?

If so, I can't update my code until this bug is fixed as batching & individual error/validation is a must for us.

**Comment by afscfl** [comment]
Hi MrSHovel, For now, what I have done is to directly post or put to the Xero API endpoint with RestRequest and pass SummarizeErrors=false as querystring.

**Comment by MrSHovel** [comment]
> Our new OAuth 2 SDKs are all being generated from our OpenAPI specs. We've seen this issue in other language SDKs and will work to address it for .NET as well.

SydenAllen, is there any update/ETA on when this issue might be addressed?
I'm committed to using the API wrapper with Batching as anything else would require large changes to our Xero export module which has been rock solid for years.

**Comment by SidneyAllen** [comment]
@jenksguo - any comment on this issue as it relates to the most recent release?

**Comment by SidneyAllen** [comment]
@afscfl @MrSHovel 

We've added the summarizeErrors param for creating multiple objects in our OpenAPI specs and generated the SDK.  We still need to test, but give it ago.

We will update once we've confirmed it's working as expected.

**Comment by MrSHovel** [comment]
Good news , I'll be working back on this next week. I pass on how it goes.

Thanks for the update...

________________________________

**Comment by jenksguo** [comment]
@afscfl @MrSHovel 

Solutions found and tested, I should be able to release the fix early next week in version 0.4.3 (regenerated against OpenAPI Spec v2.0.6).

**Comment by jenksguo** [comment]
@afscfl @MrSHovel

Issued addressed in version 0.4.3, please see release note here: 
https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v0.4.3

Thanks for reporting this issues.

**Comment by MrSHovel** [comment]
After updating to the latest version, summarise errors now works and I could create a batch of 13 Contacts in one call successfully. 

Thanks for the fix.
