### ISSUE TITLE
Money fields are 'double' not 'decimal

### ISSUE THREAD

**Issue by kiasyn** [XeroAPI/Xero-NetStandard#124]
**SDK you're using (please complete the following information):**
0.2.0? latest nuget

**Describe the bug**
All fields referring to currency are 'double' but should be decimal. Some examples:
ManualJournalLine.LineAmount
LineItem.LineAmount
LineItem.UnitAmount

etc

**To Reproduce**
N/A

**Expected behavior**
Currency fields should always be decimal

**Screenshots**
N/A

**Additional context**
"For money, always decimal. It's why it was created.

If numbers must add up correctly or balance, use decimal. This includes any financial storage or calculations, scores, or other numbers that people might do by hand.

If the exact value of numbers is not important, use double for speed. This includes graphics, physics or other physical sciences computations where there is already a "number of significant digits"."
https://stackoverflow.com/a/1165788/73135

**Comment by jenksguo** [comment]
Hi @kiasyn, thanks for providing the context and reasoning. I agree using decimal type in C# will allow developers to use financial related calculations, however because the SDK is generated off our [Xero OpenAPI specification](https://github.com/XeroAPI/Xero-OpenAPI) and the [v3 of Open API Spec ](https://github.com/XeroAPI/Xero-OpenAPI) does not support decimal type yet.

This is might be due to the the fact that decimal type is not yet supported in all major languages (currently only C#, python, Ruby and Java).

We will close this issue for now but we will look into tweaking our template to interpret certain params to decimal however at this stage the float data type and the mathematic libraries will be best we can do.

Note: 
Since v0.3.0 the data type has been changed from double to float, we have also included a unitdp parameter in the header so it supports returned number more than 2 decimals:

e.g. CreateInvoicesAsync (string accessToken, string xeroTenantId, Invoices invoices, bool? summarizeErrors = null, **int? unitdp = null**)
