### ISSUE TITLE
"ServiceCollection" does not contain a constructor that takes 0 arguments

### ISSUE THREAD

**Issue by QueenBee61** [XeroAPI/Xero-NetStandard#170]
We are using .Net Framework 4.6.1.  I I tried to use the new SDK using the solution found here: [https://github.com/XeroAPI/Xero-NetStandard/issues/132](url), but I get an error on this line:
`var serviceProvider = new ServiceCollection().AddHttpClient().BuildServiceProvider();`
That says "'ServiceCollection' does not contain a constructor that takes 0 arguments".  Does anyone know how to get past this?

**Comment by Diaho** [comment]
Try installing the DependencyInjection package, I had this issue when I started using the SDK.

Install-Package Microsoft.Extensions.DependencyInjection
Install-Package Microsoft.Extensions.Http

**Comment by jenksguo** [comment]
Hi @Diaho, could you please let me know which Visual Studio you are using with this SDK? 

I have found some challenges with VS2015 however the installation works fine in the current versions of VS2017 and VS2019.

**Comment by QueenBee61** [comment]
I am using Visual Studio 2019.

**Comment by jenksguo** [comment]
Hi @QueenBee61, it is a late solution, it appears you get this error when you use namespace

```csharp
using System.Web.Services.Description
```

instead of 

```csharp
using Microsoft.Extensions.DependencyInjection
```

[This post](https://stackoverflow.com/questions/61437571/servicecollection-does-not-contain-a-constructor-that-takes-0-arguments) provides a solution. 

Please re-open this issue if there is anything else. :-)
