### ISSUE TITLE
Does Xero-NetStandard SDK supported  paymentService now?

### ISSUE THREAD

**Issue by GavinSun9527** [XeroAPI/Xero-NetStandard#230]
Hello support,
We have an old service with c# FW 4.5.1 , and used oauth 1.0a, now we need upgrade to oauth2, we have some service request requirement in the old code, we need access payment service, Invoices , Organisation , does this SDK support these features for oauth2.0 ?

**Comment by jenksguo** [comment]
Hi @GavinSun9527, good questions. 

If you look at the [payment services guide](https://developer.xero.com/documentation/api-guides/payment-services-integration-with-xero), the payment services APIs are a collection of accounting APIs. Since accounting APIs are fully supported, the payment services APIs are as well.

**Comment by jenksguo** [comment]
Closing issue as query had been answered.
