### ISSUE TITLE
Xero.NetStandard.OAuth2.Api.PayrollAuApi.GetEmployeesAsync() returns Employees without their Pay Template

### ISSUE THREAD

**Issue by jameslow261** [XeroAPI/Xero-NetStandard#234]
**SDK you're using (please complete the following information):**

- Version 3.6.0

**Describe the bug**
The Xero.NetStandard.OAuth2.Api.PayrollAuApi.GetEmployeesAsync() method returns Employees without their Pay Template.

**To Reproduce**

1.) Call Xero.NetStandard.OAuth2.Api.PayrollAuApi.GetEmployeesAsync() passing in the required parameters.
2.) Notice the PayTemplate property of the Employees that are returned is null even if there earnings/deductions lines set up in their profile.

**Expected behavior**
The PayTemplate property of Employees should be populated with the lines in their Pay Template in their profile.

**Comment by jamie-hoffmann-xero** [comment]
Hi @jameslow261, in order to get PayTemplate with the Employee, you can use the PayrollAuApi.GetEmployeeAsync() method. By default the GetEmployeesAsync doesn't include the PayTemplate detail.

This is how the Payroll AU API behaves -- here is the documentation: https://developer.xero.com/documentation/payroll-api/employees

![image](https://user-images.githubusercontent.com/74579854/100305366-11f9ab00-2ff5-11eb-9eee-d74e2091c682.png)
