### ISSUE TITLE
invalid_grant

### ISSUE THREAD

**Issue by Mpumii02** [XeroAPI/Xero-NetStandard#257]
**XeroAPI/Xero-NetStandard API
with OAUTH2.0

**Describe the bug**
When I try to create a new invoice or contact I get an Invalid_grant error I think this may be because of an expired token question how would one go about fixing this error
**To Reproduce**
just have to try create a new invoice and the application will crash

**Comment by jamie-hoffmann-xero** [comment]
Hi @Mpumii02, thanks for raising this issue.

Are you able to provide any further information around the issue? For example, which scopes you are requesting for the token, and snippets of the code you used to create the invoice and get the token.

**Comment by jenksguo** [comment]
Hi @Mpumii02, invalid grand error occurs when you are trying to refresh an invalid refresh token. This is usually due to, failing to grab the latest refresh token or multiple clients refreshing causing other clients losing the last valid token. 

The fix to the problem is always capture the latest refresh token and use that to attempt the refresh. 

Not that refresh token itself has a 60 days lifetime so you must refresh at least every two months.
