### ISSUE TITLE
Help needed for migrating oAuth1 token to oAuth2

### ISSUE THREAD

**Issue by romil14** [XeroAPI/Xero-NetStandard#279]
Hi,

I am migrating our app from oAuth1 to oAuth2.
Also, We have a partner connection.

While migrating I am facing some difficulty, please see below questions:

1. As oAuth1 access token only valid for 30min, after that token will expired and we have to refresh access token.
    and to migrate into oAuth2 we need valid i.e. not expired oAuth1 access token.
    **Is there any other way i.e. if oAuth1 access token is expired then also we can migrate?**

2.  In Xero account in Connected App section, connected app name shows. I am connected to Xero organisation with oAuth1, 
     then in connected app section app name showing 1 time.
     With the help of "https://github.com/XeroAPI/xero-net-oauth2-sampletokenmigration" I have migrated access token oAuth1 
     to oAuth2. 
     After migrating access token, in Xero account, in Connected App section, app name showing 2 times. 
     Also, when I revoke access token then app name showing only 1 time.
     I am using "await client.RevokeAccessTokenAsync(xeroToken)" method to revoke oAuth2 token.
     **Is there any way to revoke oAuth1 access token? I am using "Xero.Api.SDK.Core" for oAuth1.**

**Comment by jenksguo** [comment]
Hi @romil14, I hope my answers below can help you. 

1. The migration endpoint will only accept currently valid OAuth 1.0a access token since we must know that customer authorisation is still there. It is also an OAuth 1.0a endpoint, so it can't work without a valid access token. You can use session_handle to refresh, then migrate. If you lost the session_handle, we consider the integration no longer authorised, so you must get the users to reconnect to OA2 rather than integrating.  

2. The app will show up twice, because they are authorised twice by a user in two authentication frameworks. This UI is undergoing some improvement changes in the future so hopefully will reduce the confusion. Sorry, we don't have a revocation method in OAuth 1.0. It is a part of the reason why we move to OAuth 2.0. In OAuth 2.0 you can disconnect an org or revoke the token completely via API.

**Comment by jenksguo** [comment]
For OAuth 1.0a , we are okay with just destroying all access tokens and session handle on your data store.
