### ISSUE TITLE
Data (Tracking categories) missing when contact is fetched by name XeroAPI

### ISSUE THREAD

**Issue by jollythakkar** [XeroAPI/Xero-NetStandard#317]
@SerKnight 

Xero.NetStandard.OAuth2 - 3.12.1
Xero.NetStandard.OAuth2Client -1.3.0

I am fetching contact's details from Xero based on name using this demo. Now the problem is,I can get contact's details but some details are always null e.g Tracking Categories.

I contacted Xero support for this. they suggested to fetch contact by GUID. But the thing is i need to fetch by name as i am searching for contacts who share same name in Xero. so there could be multiple contacts and if i fetch by name it doesn't give me tracking category details.

Here's how i am fetching contacts.

```
List<Contact> contactList = new List<Contact>();
                
var AccountingApi = new AccountingApi();
var response = await AccountingApi.GetContactsAsync(accessToken, xeroTenantId, null,
                                string.Format("FirstName != Null && FirstName.ToLower().Contains(\"{0}\")", "aaron"));

contactList = response._Contacts.ToList();
```

Contact refers to [Xero.NetStandard.OAuth2.Model.Accounting](url)
AccountingApi refers to [Xero.NetStandard.OAuth2.Api](url)

By this code i can get contacts but tracking categories are always null. How can i get all the details of contacts without searching by GUID.

Xero Contact : [https://developer.xero.com/documentation/api/contacts](url)
Tracking Categories : [https://developer.xero.com/documentation/api/tracking-categories](url)

**Comment by GraceYBR** [comment]
Hi @jollythakkar thanks for raising an issue. 

The issue you've identified is the expected behaviour of the get contacts endpoint without the use of paging. When paging is not used, the API will return a summary of each contact rather than all elements of each contact. If you implement paging then you'll find that tracking categories along with other elements will be included for each contact. The GetContactsAsync method has a page parameter that you can use.

You can find the list of elements included when you use paging by looking at the [contacts documentation](https://developer.xero.com/documentation/api/contacts#GET) and finding the sentence that says "The following are only retrieved on GET requests for a single contact or when pagination is used".

A good thing to keep in mind is that each page will be a maximum of 100 contacts, there's a section in the [contacts documentation](https://developer.xero.com/documentation/api/contacts#GET) called "Paging contacts" which will give you further details on how to use paging.

I will close this issue but feel free to reopen if you need anything further.
