### ISSUE TITLE
[PayrollAuApi] jobTitle always null when get all employees

### ISSUE THREAD

**Issue by Ma3yTa** [XeroAPI/Xero-NetStandard#323]
**SDK:**
Xero.NetStandard.OAuth2 Version 3.14.2
Xero.NetStandard.OAuth2Client Version 1.3.0

**Describe the bug**
https://developer.xero.com/documentation/payroll-api/employees
jobTitle null for all employees
if you request single Employee jobTitle sets correctly (not null)

**Expected behavior**
JobTitle not null

**Screenshots**
*JobTitle null* (PayrollAuApi.GetEmployeesAsync)
![image](https://user-images.githubusercontent.com/660379/108019865-b10acd80-704d-11eb-81bc-e917081ef76a.png)

*JobTitle set correctly* (PayrollAuApi.GetEmployeeAsync)
![image](https://user-images.githubusercontent.com/660379/108019925-d3045000-704d-11eb-9e87-8e74d97bd759.png)

**Comment by GraceYBR** [comment]
Hey @Ma3yTa, thanks for raising an issue. 

The issue you've identified is the expected behaviour of the get employees endpoint. The get employees endpoint returns a summary of all employees rather than all elements for each employee. If you want more information about each employee then you will need to get each employee individually using the EmployeeID.

If you're wanting to understand a bit more about what is returned then a good tool to use is the [API Explorer](http://api-explorer.xero.com/) which will show you example responses for API endpoints. Or, you can have a look through the employee endpoint [documentation](https://developer.xero.com/documentation/payroll-api/employees#GET).

I will close this issue but feel free to reopen if you need anything further.
