### ISSUE TITLE
filesApi.UploadFileAsync(...) adds folderId to the querystring not the path and files end up in the Inbox

### ISSUE THREAD

**Issue by rlsko** [XeroAPI/Xero-NetStandard#328]

**Comment by rlsko** [comment]
//Modified local code - Xero.NetStandard.OAuth2\Api\FilesApi.cs: Line ~1872
var url = "/Files";
if (folderId != null)
{
    url += "/" + folderId.ToString();
}
var response = await this.AsynchronousClient.PostAsync<FileObject>(url, requestOptions, this.Configuration);

**Comment by GraceYBR** [comment]
Hi @rlsko, we'd love to be able to help you but I noticed you didn't raise this issue using the template we provide. Could you please provide all the info so we can try and replicate? I've added our template below for you to copy and fill out:

**SDK you're using (please complete the following information):**
 - Version [e.g. 2.3.10]

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by rlsko** [comment]
Sorry I don't work for Vogons. I've explained the problem well enough.

**Comment by jenksguo** [comment]
@risko 

**_42_**
