### ISSUE TITLE
Too many requests error via Zapier

### ISSUE THREAD

**Issue by createdesigns** [XeroAPI/Xero-NetStandard#330]
Hello,

We're running into a lot of trouble in the past few days with XeroAPI via Zapier. We have 2 simple zaps which both fire when a Woocommerce Order is generated:

- 1st Zap - Create/Find New Contact, Create Invoice
- 2nd Zap - Create Bill

Both of these fire at the same time when an order comes in. We're processing about 50 orders per day at the moment and by about 30 orders, the API generates the Too Many Requests error (I can't see anymore information than this through Zapier annoyingly).

We have about 5000 contacts - is it possible that when the Create/Find Contact is running, when it's searching it's creating a call for every contact to check for a match?

If not, I'm really lost for ideas, we shouldn't be anywhere near the rate limits at the moment!

Apologies if this isn't quite the right place for this, but the issue seems to have only been occurring in the past week and we've never had a problem before, so I think there's potentially an issue with the API as opposed to our usage?

Thanks!

**Comment by jenksguo** [comment]
Hey @createdesigns, thanks for rising this. It looks like your Zap has hit our API rate limit documented [here](https://developer.xero.com/documentation/oauth2/limits).  

I am not sure if Zapier has the ability of "throttling" or queueing of the APIs, but if they do, please use so. 

Because your are using the Zapier to interface with Xero API, it is best if you [reach out to Zapier ](https://zapier.com/app/get-help?from_url=https%3A%2F%2Fzapier.com%2Fhelp)to help. If there is an genuine issue on Zapier - Xero integration, please let us know.

**Comment by jenksguo** [comment]
Hey @createdesigns, I hope my answer helped to clarify. Closing this for now, please re-open if there is anything related to the SDK. :-)
