### ISSUE TITLE
Could not install package in .NET Framework 4.5.2

### ISSUE THREAD

**Issue by crussman** [XeroAPI/Xero-NetStandard#335]
Greetings, how is it going?

We're currently migrating from OAuth 1 to OAuth 2, but we're experiencing some issues while trying to add the SDK NuGet packages. We're receiving the next error:

"Could not install package 'Xero.NetStandard.OAuth2 3.14.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

I searched but didn't find any versioning compatibility table between the OAuth2 SDK and the needed .NET version. Which would install for .NET 4.5.2?

In addition, I have another doubt; in case that we're not able to use the OAuth2 SDK in our project, and we generate/refresh tokens via some HTTP client like RestSharp, we'll be able to still use the SDK we used with OAuth1 (Not for generating tokens, but for getting invoices, for example)?

Thanks in advance.

Regards

**Comment by jenksguo** [comment]
Hey @crussman, unfortunately we had to drop support for any .NETFramework below v4.6.1, this is because the SDK targets NetStandard 2.0 which doesn't support anything lower. Sorry that you can't use it directly. 

Yes, the data model did not change in our API, just the Oauth 2.0 interface. You can check out our MS openid connect package example created by our Xero Developer Matt M here: 
https://github.com/XeroAPI/xero-netstandard-oauth2-samples/blob/master/XeroOAuth2Sample/XeroOAuth2Sample/XeroOAuth2Sample.csproj

**Comment by jenksguo** [comment]
Let me know if this answers your question. 😃

**Comment by james-s-tayler** [comment]
@jenksguo curious why you guys don't also generate a .NET 4.x compatible client, as open-api has a generator for .NET 4.x as well?

We have an app that's . NET 4.x and can't be upgraded to support netstandard NuGet packages even though it's running .NET 4.7.2 which is compatible with netstandard packages. In our case there are other packages we rely on that can't be upgraded to support the new package reference style that is required for using netstandard packages. 

We wound up using the open-api csharp generator ourselves.

**Comment by jenksguo** [comment]
Hey @james-s-tayler, thanks for suggesting. We have thought about doing that earlier but since the MS in general is dropping support for .NET Framework in the long term we had not invested the effort into it. 

As you may have seen from our OpenAPI spec, we had to use plenty of vendor extensions to make a few things work with the OpenAPI spec 3.0 and the generator we use to interpret "double" to "decimal" for numbers that is related to monetary calculations. 

We had customised and tweak the template quite a bit to make it work with our specific API sets (which are not completely consistent). We also intent to open our template in the future so developers can use our template to generate working examples, but first we will need full test coverage and get few more improvements done. 

Because of the efforts involved, we have not yet considered building to other versions of .NET yet.

We do encourage developers like you to try generate and make it available for others to use. Happy to answer your questions.

**Comment by james-s-tayler** [comment]
Thanks @jenksguo  that's really valuable info. Unfortunately it leaves us in a pretty bad spot. It likely means we'll have to generate it with the csharp generator and then manually convert a bunch of fields to decimal. It means upgrading to newer versions of the Accounting API open API definition will be difficult and risky, and therefore won't happen which may bring its own problems. 

Either that or we basically have to go right back to square one and just write all the models we use by hand which seems like the worst of both worlds. 

:(

Any additional info you can provide about what your generator does that's different would be very helpful in getting us to a point where our models match the ones generated by your generator, so they match and we don't keep finding these little inconsistencies between our implementations.

**Comment by james-s-tayler** [comment]
@jenksguo I have an idea that could enable pretty good .NET 4.x support using your existing generator and without much work. 

All we really need are the models. Typically I prefer an HttpClient based approach and using Refit and some DelegatingHandlers it's very quick to slap together you're own SDK that leaves you in full control of the HTTP requests. 

Can you run it by the team to possibly put together a script that simply copies the source of only the models generated by your generator into a .NET 4.x library, and publish a NuGet package of only the models?

I think that'd be fairly low effort, and could be put Into a CI/CD pipeline that trigger when the open API spec is updated, so we could keep up to date with official support. 

Does that sound reasonable?

**Comment by crussman** [comment]
Hi! Sorry for the delay, I was really busy and didn't enter much here.

We decided to delete the Xero SDK from our projects and move all the integration to a HTTP Cliente approach, because the SDK we used (Minimal) wasn't compatible with OAuth2 tokens, so instead of that, we changed our internal implementations where the SDK was being called, and replaced it with RestSharp calls.

Anyway, thanks for your support, I suppose I can close this issue now.

Have a great day
