### ISSUE TITLE
Support for Custom Connections

### ISSUE THREAD

**Issue by gatapia** [XeroAPI/Xero-NetStandard#365]
**SDK you're using (please complete the following information):**
Latest

**Is your feature request related to a problem? Please describe.**
It appears that this client SDK does not support the new Custom Connections.

**Describe the solution you'd like**
Support Custom Connections, i.e. Support Client ID + Client Secret with no callback url

**Describe alternatives you've considered**
Using raw HTTP calls, which will work but its ugly even when using a good http client library (like restsharp)

**Comment by mattpawson** [comment]
+ 1 for this

Do you have any timelines for when this might happen?

With the deadline for apps being upgraded set for 30th September, we would need the SDK updated relatively soon to allow developers to integrate with it.

If the SDK isn't going to be ready by mid-August, or there are no plans to update, then please let the community know so that we can build out own solutions.

**Comment by SerKnight** [comment]
Hi @gatapia and @mattpawson - we are in development for this. We've got Customs available in 4/6 of the SDKs and this repo is up next. Should expect to see a release by mid next week at the latest.

**Comment by Tyf0x** [comment]
Thank you @SerKnight.

I've see some code land in this regard, can we assume this SDK now supports Custom Connections?

If yes, is there any documentation you could point me towards that illustrates how to authenticate using CC please?

Thank you :)

**Comment by SerKnight** [comment]
Hi @Tyf0x @mattpawson and @gatapia 

Code and documentation have been released.

https://github.com/XeroAPI/Xero-NetStandard#custom-connections

Note that this is using `1.4.0`

https://github.com/XeroAPI/Xero-NetStandard-custom-connections-starter/blob/master/csharp.csproj#L12
