### ISSUE TITLE
Create Task Missing

### ISSUE THREAD

**Issue by oharper** [XeroAPI/Xero-NetStandard#422]
I don't seem to be able to see a method for Creating tasks on a Project, is this meant to be there?

**Comment by RettBehrens** [comment]
Good catch! Looks like they [commented out](https://github.com/XeroAPI/Xero-OpenAPI/blob/master/xero-projects.yaml) at one time because they weren't working as expected. I've just tested all the endpoints via Insomnia and they're working so we'll look to generate and test an update to the SDKs and hopefully have this rolled out next week

**Comment by oharper** [comment]
Ah great, thank you!

**Comment by oharper** [comment]
@RettBehrens Any luck with this one? :)

**Comment by RettBehrens** [comment]
Just released into the wild https://github.com/XeroAPI/Xero-NetStandard/releases/tag/3.26.0
