### ISSUE TITLE
Bug when use MVC app as a private application

### ISSUE THREAD

**Issue by AKlaus** [XeroAPI/Xero-NetStandard#68]
`Xero.Api.Example.MVC` throws "_MVC cannot be used with private applications_" exception when the application type is set to `Private` ([code link](https://github.com/XeroAPI/Xero-NetStandard/blob/3f25abcc1d730af22915959a773b326d7d99c181/Xero.Api.Example.MVC/Helpers/XeroApiHelper.cs#L46)).
It seems to be a bug, unless I'm trying to do something inappropriate.

**Comment by MJMortimer** [comment]
We've explicitly not included an MVC example for use with private applications because only one organisation can be connected to them and that connection between a private app and an organisation is created during the apps creation.

We've included the MVC examples for public and partner applications because these application types require actions by each user wanting to connect an organisation to the application.
