### ISSUE TITLE
Override User Agent Name

### ISSUE THREAD

**Issue by markogrady** [XeroAPI/Xero-NetStandard#7]
Hi Should there be an override for the user agent or you keeping it there so you know who is using the netstandard api? if so should we change it so the start of the user agents is netstand - *CustomAgent* - consumerkey

https://github.com/XeroAPI/Xero-NetStandard/blob/6bb166797ddcc8ecf4bfd39c9ef5c792b7697fe2/Xero.Api/Infrastructure/Http/XeroHttpClient.cs#L205

**Comment by MJMortimer** [comment]
Ideally, I'd like to keep it consistent across all users of this SDK, as it really helps us out when helping end users having issues if we can correlate different users issues with specific SDKs etc.

Is not being able to set the UserAgent a blocker for you or were you just interested in the reasoning behind not being able to change it?

**Comment by markogrady** [comment]
James Coleman the UK Dev Evangelist said it is one of the things that needs changing for the partner status. I can understand your reasoning because the consumerkey is included. Should I tell him you want ot keep it this way?

**Comment by MJMortimer** [comment]
We could always build a way where the user can assign their own user agent and it just becomes additive to the default one? So the default one with the consumer key is added as a suffix to a possible user defined user agent

**Comment by markogrady** [comment]
Sure do you me to make the change?

**Comment by MJMortimer** [comment]
Yeah if you want to make the change that would be great!

**Comment by MJMortimer** [comment]
I would assume it would look very much the opposite of this haha: https://github.com/XeroAPI/Xero-NetStandard/commit/23a260da03b3be481d3c841c2a59fa7288e67af4

**Comment by MJMortimer** [comment]
Resolved in #9

**Comment by gthompson121** [comment]
I have recently been applying to be a "Partner" of Xero and my code has been reviewed by them similar to @markogrady. One of the issues they flagged was that the user agent was not in a suitable format and it would need to be changed in order to pass the review. They requested that the user agent was simply the name of my own application which is currently not possible with the implementation. If it is their stance that the user agent needs to be custom then should we not follow this also?

Apologies for bumping this closed issue but thought my experience was worth sharing.
