### ISSUE TITLE
Use IHttpClientFactory instead of 'new HttpClient'

### ISSUE THREAD

**Issue by mjrmua** [XeroAPI/Xero-NetStandard#78]
So that we can configure a proxy for the calls to Xero

**Comment by MJMortimer** [comment]
Hi @mjrmua, This is a good suggestion. 
Is this functionality something you'd be comfortable adding via a pull request?

**Comment by cdenvir** [comment]
Could you please make IHttpClientFactory optional and allow new HttpClient again, it's broken the code samples and made running a simple test in a console impossible without having to use dependency injection

**Comment by KenYarborough** [comment]
Note that the name of this project is "Xero-NetStandard"

Multiple programmers have mentioned IHttpClientFactory breaks the code.

The reason is simple: IHttpClientFactory is a DotNet core feature (added in DotNet Core 2.1)

The HttpClientFactory is fantastic if you're the 5% using DotNet Core, and the library was called "Xero-NetCore" 

Not useful in a library called "Xero-NetStandard"

I'm not the first programmer to report this problem.

I'm really irritated that the only documentation is in the "MD" file, which @jenksguo updated, without obviously testing, and then immediately closed.

He just passed the buck. In the code example buried in the MD file:

1) by making a class with "using Microsoft.AspNetCore.Mvc;"

2) with the note "a .NET Core Mvc example:"

3) meaning you have to call the class from DotNet core class to make work. 

Sort of defeats the purpose of a library called "Xero-NetStandard"

So to repeat myself: if a library is called "Xero-NetStandard", no one is interested in a "a .NET Core Mvc example:"

Please fix. Some of us are actually trying to use a Xero.

**Comment by MJMortimer** [comment]
It looks like there are a couple of things to address in here.

First off, due to the date that the initial issue was opened, the issue was raised for the OAuth1.0a SDK, and no changes have been made to address this. As the SDK is now in a strict maintenance phase we won't be making any related changes to the OAuth1.0a SDK.

@cdenvir Can you please confirm what SDK/sample you are having issues with. If there is a problem with the OAuth2.0 SDK, can I please request that you open a new issue, or reopen this one.

Cheers,
Matt
